plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'ui.javafx'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = '21.0.5'
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'ui.javafx.app.MainApp'
}

run {
    workingDir = file("$rootDir/core")
    systemProperty 'file.encoding', 'UTF-8'
    systemProperty 'stdout.encoding', 'UTF-8'
}


dependencies {
    implementation project(':core')
}