plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'ui.javafx'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}


javafx {
    version = '21.0.5'
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'ui.javafx.app.MainApp'
}

run {
    workingDir = file("$rootDir/core")
}


dependencies {
    implementation project(':core')
}