plugins {
    id 'java'
}

dependencies {
    implementation project(':core')

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'

    implementation 'org.jfree:jfreechart:1.5.4'
}

repositories {
    mavenCentral()
}


tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}